# This workflow will use multiple Veracode GitHub Actions from marketplace

name: Veracode GHActions demo

on:
#  push:
#    branches: [ master, '*' ]
  workflow_dispatch:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, '*' ]
  schedule:
    - cron: '17 5 * * 2'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it, build, and upload artifact. Replace this section with your applications build steps
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/upload-artifact@v1
      with:
        name: verademo.war
        path: target/verademo.war
        
 # Below is copy/paste from Marketplace     
    
    - name: Veracode Upload And Scan
    # You may pin to the exact commit or the version.
    # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      uses: veracode/veracode-uploadandscan-action@0.2.1
      with:
        # appname
        appname: ${{ github.repository }}
        # createprofile
        createprofile: false
        # filepath
        filepath: target/verademo.war
        # version
        version: ${{ github.run_id }}
        # vid
        vid: '${{secrets.VERACODE_API_ID}}'
        # vkey
        vkey: '${{secrets.VERACODE_API_KEY}}'
        # true or flase
        createsandbox: true
        # name of the sandbox
        sandboxname: GHviaMarketplace
        # wait X minutes for the scan to complete
        scantimeout: 60
#         # modules to exclude from module selection
#         exclude: # optional
#         # modules to include in module selection
#         include: # optional
#         # business criticality - policy selection
#         criticality: # optional
#         # filename pattern
#         pattern: # optional
#         # replacement
#         replacement: # optional
#         # replacement
#         sandboxid: # optional
#         # All top level modules
#         scanallnonfataltoplevelmodules: # optional
#         # platform selected modules
#         selected: # optional
#         # selected modules like from previous scan
#         selectedpreviously: # optional
#         # teams
#         teams: # optional
#         # teams
#         toplevel: # optional  
